name: Docs

on: [push, pull_request]

jobs:
  build-docs:
    strategy:
      matrix:
        python-version:
          - '3.9'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Need full history to determine version number.
        fetch-depth: 0
    - name: 'Set up Python ${{ matrix.python-version }}'
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: 'Configure bazel remote cache write credentials'
      env:
        BAZEL_CACHE_SERVICE_ACCOUNT_KEY: ${{ secrets.BAZEL_CACHE_SERVICE_ACCOUNT_KEY }}
      run: python ./tools/ci/configure_bazel_remote_cache.py --bazelrc ~/ci_bazelrc docs
      shell: bash
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
    - uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: pip-${{ runner.os }}-docs-${{ matrix.python-version }}-${{ hashFiles('third_party/pypa/workspace.bzl') }}
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/bazel/_bazel_*/cache/repos
          ~/.cache/bazelisk
        key: bazel-docs-${{ hashFiles('.bazelversion', 'WORKSPACE', 'external.bzl', 'third_party/**') }}
    - name: Build documentation
      run: CC=gcc-10 python -u bazelisk.py --bazelrc ~/ci_bazelrc run --announce_rc --show_timestamps --keep_going --color=yes --verbose_failures //docs:build_docs -- --output docs_output
      shell: bash
    - name: Upload docs as artifact
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs_output

  publish-docs:
    # Only publish package on push to tag or default branch.
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs:
      - build-docs
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: docs
        path: docs_output
    - name: Publish to gh-pages
      uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501 # v3.7.3 (2020-10-20)
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs_output
